language: node_js
node_js:
- '0.12'
- '0.11'
env:
  global:
    secure: IxaUOo3m9M30UxgPuns9Ez8zBonQhDtAmaIFd2O0gOr3i578JHMokxBHJbyfhJ0laNO9iHBRpmfeL3AITegB2FVZ64eH+afzuxeRyHGUvEcEdJiTS9Py9ZGFFKv4qbVDaUQeKYHBYpqRnqZi1emjMCaHcX3XRDzYnoGv6/FOmQg=
